version: 0.2
phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - mkdir artifact
      - mv dist/ artifact/
      - mv package.json artifact/
      - mv openmed-api.service artifact/
artifacts:
  files:
    - artifact/*
