version: 0.2
key-pairs:
  ec2key: "arn:aws:secretsmanager:us-east-1:421914042095:secret:ec2desakey-cW1p8R"
phases:
  pre_build:
    commands:
      - scp -i $ec2key ./**/* ubuntu@54.198.139.215:/home/ubuntu
  build:
    commands:
      - ssh -i $ec2key ubuntu@54.198.139.215
      - sudo rm -r /opt/api/dist/
      - sudo mv ./**/* /opt/api
      - cd /opt/api | npm install
      - sudo systemctl stop openmed-api.service
      - sudo systemctl start openmed-api.service
  post_build:
    commands:
      - sudo systemctl status openmed-api.service
